#####################################################################
# Basics
#####################################################################
[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/mks/printer_data/comms/klippy.sock

[authorization]
force_logins: True
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    http://*.lan
    http://*.local
    https://my.mainsail.xyz
    http://my.mainsail.xyz
    https://app.fluidd.xyz
    http://app.fluidd.xyz
    http://*.qidi3dprinter.com
    https://*.qidi3dprinter.com
max_login_attempts: 5


#####################################################################
# Features
#####################################################################
[octoprint_compat]

[history]

# For kemp, see https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging
[file_manager]
enable_object_processing: True

[announcements]
subscriptions:
  FreeDi

[spoolman]
server: http://10.1.10.16:7912
sync_rate: 5

[timelapse]
output_path: ~/printer_data/timelapse/
frame_path: /tmp/timelapse/printer

#####################################################################
# cams
#####################################################################
#[webcam cam1]
# The URL for the webcam stream (typically port 8080 or 81 with webcam software like crowsnest)
#stream_url: http://127.0.0.1:8080/?action=stream
# The URL used to capture still snapshots (often used for timelapse)
#snapshot_url: http://127.0.0.1:8080/?action=snapshot

#####################################################################
# Update Mangers
#####################################################################
[update_manager]
channel: stable
refresh_interval: 168

# Mainsail update_manager entry
[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
install_script: tools/pkglist.sh

# FreeDi update_manager entry
[update_manager FreeDi]
type: git_repo
path: ~/FreeDi
channel: stable
origin: https://github.com/Phil1988/FreeDi
virtualenv: ~/klippy-env
requirements: requirements.txt
managed_services: FreeDi
info_tags:
	desc=FreeDi

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[update_manager cartographer_plugin]
type: python
channel: stable
virtualenv: ~/klippy-env
project_name: cartographer3d-plugin
is_system_service: False
managed_services: klipper
info_tags: desc=Cartographer Plugin

[update_manager Cartographer Firmware]
type: git_repo
path: ~/cartographer_firmware
origin: https://github.com/Cartographer3D/cartographer_firmware.git
is_system_service: False

[update_manager katapult]
type: git_repo
path: ~/katapult
is_system_service: False
origin: https://github.com/Arksine/katapult.git

[update_manager mobileraker]
install_script: /home/mks/mobileraker_companion/scripts/install.sh
requirements: /home/mks/mobileraker_companion/scripts/mobileraker-requirements.txt
env: /home/mks/mobileraker-env/bin/python
managed_services: mobileraker
primary_branch: main
origin: https://github.com/Clon1998/mobileraker_companion.git
path: /home/mks/mobileraker_companion
type: git_repo

[update_manager happy-hare]
type: git_repo
path: ~/Happy-Hare
origin: https://github.com/moggieuk/Happy-Hare.git
primary_branch: main
managed_services: klipper

[mmu_server]
enable_file_preprocessor: True
enable_toolchange_next_pos: True
update_spoolman_location: True

[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main

[include moonraker-obico-update.cfg]
